name: GitHub Actions Build and Deploy Demo
strategy:
    matrix:
        node-version: 14.x
on:
    push:
        branches:
            - main
            - f_saiye_token

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
              with:
                  persist-credentials: false
            - name: Install and Build
              run: |
                  npm install lerna -g
                  lerna bootstrap
                  npm run-script docs:ci
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: build
